#!/bin/bash 

skrypt.sh:

suma = 0
for val in "$@"
do
   suma = $((suma + val))
done 
echo $suma

suma = 0;
while [-n "$1"]
do 
   suma = $((suma + $1))
done 
echo $suma 

"$1"="="
$1==

suma = 0
for val in "$@"
do
   if ["$val"="="]
   then
      echo $suma
      suma=0
    else 
      suma = $((suma + val))
done 
echo $suma

suma = 0;
while [-n "$1" -a "$1"!="="]
do 
   suma = $((suma + $1))
done 
echo $suma 

145=246=4=83